/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha2 "sigs.k8s.io/gateway-api/apis/v1alpha2"
	scheme "sigs.k8s.io/gateway-api/pkg/client/clientset/versioned/scheme"
)

// EgressRoutesGetter has a method to return a EgressRouteInterface.
// A group's client should implement this interface.
type EgressRoutesGetter interface {
	EgressRoutes(namespace string) EgressRouteInterface
}

// EgressRouteInterface has methods to work with EgressRoute resources.
type EgressRouteInterface interface {
	Create(ctx context.Context, egressRoute *v1alpha2.EgressRoute, opts v1.CreateOptions) (*v1alpha2.EgressRoute, error)
	Update(ctx context.Context, egressRoute *v1alpha2.EgressRoute, opts v1.UpdateOptions) (*v1alpha2.EgressRoute, error)
	UpdateStatus(ctx context.Context, egressRoute *v1alpha2.EgressRoute, opts v1.UpdateOptions) (*v1alpha2.EgressRoute, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha2.EgressRoute, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha2.EgressRouteList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.EgressRoute, err error)
	EgressRouteExpansion
}

// egressRoutes implements EgressRouteInterface
type egressRoutes struct {
	client rest.Interface
	ns     string
}

// newEgressRoutes returns a EgressRoutes
func newEgressRoutes(c *GatewayV1alpha2Client, namespace string) *egressRoutes {
	return &egressRoutes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the egressRoute, and returns the corresponding egressRoute object, and an error if there is any.
func (c *egressRoutes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.EgressRoute, err error) {
	result = &v1alpha2.EgressRoute{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("egressroutes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EgressRoutes that match those selectors.
func (c *egressRoutes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.EgressRouteList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha2.EgressRouteList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("egressroutes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested egressRoutes.
func (c *egressRoutes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("egressroutes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a egressRoute and creates it.  Returns the server's representation of the egressRoute, and an error, if there is any.
func (c *egressRoutes) Create(ctx context.Context, egressRoute *v1alpha2.EgressRoute, opts v1.CreateOptions) (result *v1alpha2.EgressRoute, err error) {
	result = &v1alpha2.EgressRoute{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("egressroutes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(egressRoute).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a egressRoute and updates it. Returns the server's representation of the egressRoute, and an error, if there is any.
func (c *egressRoutes) Update(ctx context.Context, egressRoute *v1alpha2.EgressRoute, opts v1.UpdateOptions) (result *v1alpha2.EgressRoute, err error) {
	result = &v1alpha2.EgressRoute{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("egressroutes").
		Name(egressRoute.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(egressRoute).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *egressRoutes) UpdateStatus(ctx context.Context, egressRoute *v1alpha2.EgressRoute, opts v1.UpdateOptions) (result *v1alpha2.EgressRoute, err error) {
	result = &v1alpha2.EgressRoute{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("egressroutes").
		Name(egressRoute.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(egressRoute).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the egressRoute and deletes it. Returns an error if one occurs.
func (c *egressRoutes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("egressroutes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *egressRoutes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("egressroutes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched egressRoute.
func (c *egressRoutes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.EgressRoute, err error) {
	result = &v1alpha2.EgressRoute{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("egressroutes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
