/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha2 "sigs.k8s.io/gateway-api/apis/v1alpha2"
)

// FakeEgressRoutes implements EgressRouteInterface
type FakeEgressRoutes struct {
	Fake *FakeGatewayV1alpha2
	ns   string
}

var egressroutesResource = v1alpha2.SchemeGroupVersion.WithResource("egressroutes")

var egressroutesKind = v1alpha2.SchemeGroupVersion.WithKind("EgressRoute")

// Get takes name of the egressRoute, and returns the corresponding egressRoute object, and an error if there is any.
func (c *FakeEgressRoutes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.EgressRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(egressroutesResource, c.ns, name), &v1alpha2.EgressRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.EgressRoute), err
}

// List takes label and field selectors, and returns the list of EgressRoutes that match those selectors.
func (c *FakeEgressRoutes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.EgressRouteList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(egressroutesResource, egressroutesKind, c.ns, opts), &v1alpha2.EgressRouteList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.EgressRouteList{ListMeta: obj.(*v1alpha2.EgressRouteList).ListMeta}
	for _, item := range obj.(*v1alpha2.EgressRouteList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested egressRoutes.
func (c *FakeEgressRoutes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(egressroutesResource, c.ns, opts))

}

// Create takes the representation of a egressRoute and creates it.  Returns the server's representation of the egressRoute, and an error, if there is any.
func (c *FakeEgressRoutes) Create(ctx context.Context, egressRoute *v1alpha2.EgressRoute, opts v1.CreateOptions) (result *v1alpha2.EgressRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(egressroutesResource, c.ns, egressRoute), &v1alpha2.EgressRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.EgressRoute), err
}

// Update takes the representation of a egressRoute and updates it. Returns the server's representation of the egressRoute, and an error, if there is any.
func (c *FakeEgressRoutes) Update(ctx context.Context, egressRoute *v1alpha2.EgressRoute, opts v1.UpdateOptions) (result *v1alpha2.EgressRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(egressroutesResource, c.ns, egressRoute), &v1alpha2.EgressRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.EgressRoute), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEgressRoutes) UpdateStatus(ctx context.Context, egressRoute *v1alpha2.EgressRoute, opts v1.UpdateOptions) (*v1alpha2.EgressRoute, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(egressroutesResource, "status", c.ns, egressRoute), &v1alpha2.EgressRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.EgressRoute), err
}

// Delete takes name of the egressRoute and deletes it. Returns an error if one occurs.
func (c *FakeEgressRoutes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(egressroutesResource, c.ns, name, opts), &v1alpha2.EgressRoute{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEgressRoutes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(egressroutesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha2.EgressRouteList{})
	return err
}

// Patch applies the patch and returns the patched egressRoute.
func (c *FakeEgressRoutes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.EgressRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(egressroutesResource, c.ns, name, pt, data, subresources...), &v1alpha2.EgressRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.EgressRoute), err
}
